name: Release
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Expo Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf install
        uses: asdf-vm/actions/install@v1
        env:
          NODEJS_CHECK_SIGNATURES: "no"
      - name: Set global nodejs and yarn version
        run: |
          asdf global nodejs `asdf current nodejs | cut -d " " -f1`
          asdf global yarn `asdf current yarn | cut -d " " -f1`
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
          expo-cache: true
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        uses: codfish/semantic-release-action@master
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Expo publish
        run: |
          expo publish
  